[2024-10-16 14:53:06,075] torch.distributed.run: [WARNING] 
[2024-10-16 14:53:06,075] torch.distributed.run: [WARNING] *****************************************
[2024-10-16 14:53:06,075] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-10-16 14:53:06,075] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 140, in <module>
    main()
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 85, in main
    if cfg.run_cfg.prefix:
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key prefix
    full_key: run.prefix
    object_type=dict
Traceback (most recent call last):
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 140, in <module>
Traceback (most recent call last):
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 140, in <module>
    main()    
main()  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 85, in main

  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 85, in main
    if cfg.run_cfg.prefix:
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    if cfg.run_cfg.prefix:    
self._format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    self._format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    _raise(ex, cause)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace    
format_and_raise(  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__

  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    return self._get_impl(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    _raise(ex, cause)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    node = self._get_child(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
      File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
        return self._get_impl(raise ConfigKeyError(f"Missing key {key!s}")

  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
omegaconf.errors.    ConfigAttributeErrornode = self._get_child(: 
Missing key prefix
    full_key: run.prefix
    object_type=dict  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child

    child = self._get_node(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key prefix
    full_key: run.prefix
    object_type=dict
Traceback (most recent call last):
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 140, in <module>
    main()
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 85, in main
    if cfg.run_cfg.prefix:
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key prefix
    full_key: run.prefix
    object_type=dict
[2024-10-16 14:53:16,095] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1705962) of binary: /home/tom/.conda/envs/malmm/bin/python3.10
Traceback (most recent call last):
  File "/home/tom/.conda/envs/malmm/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-16_14:53:16
  host      : localhost
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1705963)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-16_14:53:16
  host      : localhost
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1705964)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-10-16_14:53:16
  host      : localhost
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1705965)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-16_14:53:16
  host      : localhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1705962)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
[2024-10-16 14:53:51,952] torch.distributed.run: [WARNING] 
[2024-10-16 14:53:51,952] torch.distributed.run: [WARNING] *****************************************
[2024-10-16 14:53:51,952] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-10-16 14:53:51,952] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 140, in <module>
    main()
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 85, in main
    if cfg.run_cfg.prefix:
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key prefix
    full_key: run.prefix
    object_type=dict
Traceback (most recent call last):
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 140, in <module>
    main()
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 85, in main
    if cfg.run_cfg.prefix:
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key prefix
    full_key: run.prefix
    object_type=dict
Traceback (most recent call last):
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 140, in <module>
    main()
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 85, in main
    if cfg.run_cfg.prefix:
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key prefix
    full_key: run.prefix
    object_type=dict
Traceback (most recent call last):
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 140, in <module>
    main()
  File "/home/tom/Open-Sora-dev/tools/scoring/MA-LMM/train.py", line 85, in main
    if cfg.run_cfg.prefix:
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key prefix
    full_key: run.prefix
    object_type=dict
[2024-10-16 14:54:01,975] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1713490) of binary: /home/tom/.conda/envs/malmm/bin/python3.10
Traceback (most recent call last):
  File "/home/tom/.conda/envs/malmm/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tom/.conda/envs/malmm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-16_14:54:01
  host      : localhost
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1713491)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-16_14:54:01
  host      : localhost
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1713492)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-10-16_14:54:01
  host      : localhost
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1713493)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-16_14:54:01
  host      : localhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1713490)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
